### ISSUE TITLE
Sample apps won't compile

### ISSUE THREAD

**Issue by WedaPashi10** [pokowaka/jwt-cpp#14]
Hi, I just installed this library. The first thing I wanted to do is try a sample application it contains.
Build it with the steps specified in README.md.
I have also installed nlohmann json library.

Generated following error:

/tmp/ccII9c8j.o: In function `main':
sign.cpp:(.text+0x24e): undefined reference to `JWT::Encode(MessageSigner const&, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> const&, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>)'
/tmp/ccII9c8j.o: In function `HS256Validator::HS256Validator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
sign.cpp:(.text._ZN14HS256ValidatorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN14HS256ValidatorC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x21): undefined reference to `EVP_sha256'
sign.cpp:(.text._ZN14HS256ValidatorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN14HS256ValidatorC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x5f): undefined reference to `HMACValidator::HMACValidator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, evp_md_st const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccII9c8j.o:(.rodata._ZTV14HS256Validator[_ZTV14HS256Validator]+0x20): undefined reference to `HMACValidator::Verify(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> const&, unsigned char const*, unsigned long, unsigned char const*, unsigned long) const'
/tmp/ccII9c8j.o:(.rodata._ZTV14HS256Validator[_ZTV14HS256Validator]+0x28): undefined reference to `HMACValidator::toJson[abi:cxx11]() const'
/tmp/ccII9c8j.o:(.rodata._ZTV14HS256Validator[_ZTV14HS256Validator]+0x38): undefined reference to `MessageValidator::Accepts(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> const&) const'
/tmp/ccII9c8j.o:(.rodata._ZTV14HS256Validator[_ZTV14HS256Validator]+0x40): undefined reference to `HMACValidator::Sign(unsigned char const*, unsigned long, unsigned char*, unsigned long*) const'
/tmp/ccII9c8j.o: In function `HS256Validator::~HS256Validator()':
sign.cpp:(.text._ZN14HS256ValidatorD2Ev[_ZN14HS256ValidatorD5Ev]+0x20): undefined reference to `HMACValidator::~HMACValidator()'
/tmp/ccII9c8j.o:(.rodata._ZTI14HS256Validator[_ZTI14HS256Validator]+0x10): undefined reference to `typeinfo for HMACValidator'
collect2: error: ld returned 1 exit status`

**Comment by pokowaka** [comment]
The nhlohman library is header only so that’s not the problem. From the errors it looks like you are not linking against the ssl library as well as the jwt library.

**Comment by WedaPashi10** [comment]
Well, resolved it. 
I needed to change 
`g++ std=c++11 -I /usr/local/include -L/usr/local/lib -lcrypto -ljwt sign.c -o sign`     
to  
`g++ std=c++11 sign.c -o sign -lcrypto -ljwt`

Reason: The unix linker doesn't look backwards in the command line to resolve dependencies. [More information on this can be referred here](https://stackoverflow.com/a/11894098/4228131) and [here](https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc)

**Comment by pokowaka** [comment]
Oh wow, maybe I should update the samples so others don't run into this.
