### ISSUE TITLE
Support that the last character in the jwt token is \n

### ISSUE THREAD

**Issue by hestad** [pokowaka/jwt-cpp#29]
We are reading the jwt-token from file and many editors adds a \n, which fails in the base64-check.

**Comment by pokowaka** [comment]
Can't you just trim the string as in: https://stackoverflow.com/questions/216823/whats-the-best-way-to-trim-stdstring?

I don't think the newline is part of the spec, and might cause unexpected behavior.

**Comment by hestad** [comment]
Yeah, that's exactly what I ended up doing.
